services:
  node-app:
    container_name: express-node-app-container
    image: madinor/nor-docker
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      # - mongo
      - redis
      # - postgres
  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: example
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data
  
  
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH_ENABLED: "true"
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: example
  #   depends_on:
  #     - mongo
  redis:
    image: redis
    ports:
      - 6379:6379
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-db:
  # postgres-db:
  
    
    